### ISSUE TITLE
Build failure: File not found

### ISSUE THREAD

**Issue by ColtonProvias** [ember-cli/ember-load-initializers#25]
Version used: 0.5.1

```
ENOENT: no such file or directory, stat '/Users/coltonprovias/Development/MyNewLeaf-KeyGrinder/tmp/concat_with_maps-input_base_path-AeKvMYqz.tmp/0/bower_components/ember-load-initializers/ember-load-initializers.js'
Error: ENOENT: no such file or directory, stat '/Users/coltonprovias/Development/MyNewLeaf-KeyGrinder/tmp/concat_with_maps-input_base_path-AeKvMYqz.tmp/0/bower_components/ember-load-initializers/ember-load-initializers.js'
    at Error (native)
    at Object.fs.statSync (fs.js:892:18)
    at ConcatWithMaps.keyForFile (/Users/coltonprovias/Development/MyNewLeaf-KeyGrinder/node_modules/broccoli-caching-writer/index.js:90:20)
    at Array.map (native)
    at ConcatWithMaps.CachingWriter._conditionalBuild (/Users/coltonprovias/Development/MyNewLeaf-KeyGrinder/node_modules/broccoli-caching-writer/index.js:112:65)
    at /Users/coltonprovias/Development/MyNewLeaf-KeyGrinder/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/Users/coltonprovias/Development/MyNewLeaf-KeyGrinder/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/coltonprovias/Development/MyNewLeaf-KeyGrinder/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/Users/coltonprovias/Development/MyNewLeaf-KeyGrinder/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/Users/coltonprovias/Development/MyNewLeaf-KeyGrinder/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
```

**Comment by rwjblue** [comment]
v0.5.1 is not usable as a bower component, please continue to use the version that was blueprinted for your app (I believe it is 0.1.7).

**Comment by rwjblue** [comment]
ember-cli@2.3.0-beta.2 will use ember-load-initializers as an addon

**Comment by rwjblue** [comment]
If you have time, I'd love a PR adding some info about this to the README...
